import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import { cleanJpeg, parseJpeg } from '../src/engine/jpeg.js';
import { cleanPng, parsePng } from '../src/engine/png.js';
import { cleanWebp, parseWebp } from '../src/engine/webp.js';
import { analyze } from '../src/engine/analyze.js';
import { clean } from '../src/engine/clean.js';
import { sha256 } from '../src/utils/crypto.js';

const marker=(m:number,payload:Buffer)=>Buffer.concat([Buffer.from([0xff,m,(payload.length+2)>>8,(payload.length+2)&255]),payload]);
const makeJpegFixture=(base:Buffer)=>Buffer.concat([base.subarray(0,2),marker(0xe1,Buffer.from('Exif\0\0FAKE-EXIF')) , marker(0xed,Buffer.from('FAKE-IPTC')), marker(0xeb,Buffer.from('JUMBF\0c2pa fake manifest')), marker(0xfe,Buffer.from('comment')), base.subarray(2)]);
const pngChunk=(type:string,data:Buffer)=>{const out=Buffer.alloc(12+data.length);out.writeUInt32BE(data.length,0);out.write(type,4,'ascii');data.copy(out,8);out.writeUInt32BE(0,8+data.length);return out;};
const injectPng=(base:Buffer)=>{const idx=base.indexOf(Buffer.from('IEND'))-4; return Buffer.concat([base.subarray(0,8),pngChunk('tEXt',Buffer.from('Author\0Ada')),pngChunk('eXIf',Buffer.from('EXIF fake')),pngChunk('caBX',Buffer.from('JUMBF c2pa')),base.subarray(8,idx),base.subarray(idx)]);};

test('JPEG surgical removal preserves scan bytes', async()=>{const base=await sharp({create:{width:64,height:64,channels:3,background:{r:50,g:80,b:120}}}).jpeg({quality:90}).toBuffer();const fixture=makeJpegFixture(base);const cleaned=cleanJpeg(fixture,new Set(['everything']));const p1=parseJpeg(fixture),p2=parseJpeg(cleaned);assert.equal(p1.sosOffset>=0,true);assert.equal(sha256(fixture.subarray(p1.sosOffset)),sha256(cleaned.subarray(p2.sosOffset)));assert.equal(parseJpeg(cleaned).items.some(x=>x.group==='c2pa'),false);assert.equal(parseJpeg(cleaned).items.some(x=>x.group==='exif'),false);});

test('PNG chunk removal preserves IDAT bytes', async()=>{const base=await sharp({create:{width:32,height:32,channels:4,background:{r:10,g:20,b:30,alpha:.5}}}).png().toBuffer();const fixture=injectPng(base);const before=parsePng(fixture), after=parsePng(cleanPng(fixture,new Set(['everything'])));const a=before.chunks.filter(c=>c.type==='IDAT').map(c=>sha256(c.data)).join('');const b=after.chunks.filter(c=>c.type==='IDAT').map(c=>sha256(c.data)).join('');assert.equal(a,b);assert.equal(after.items.some(x=>x.group==='exif'||x.group==='c2pa'||x.group==='other'),false);});

test('WebP metadata chunks are removed without touching image chunks', async()=>{const base=await sharp({create:{width:48,height:48,channels:3,background:{r:200,g:120,b:40}}}).webp().toBuffer(); const orig=parseWebp(base); const imageChunks=orig.chunks.map(c=>base.subarray(c.start,c.end)); const make=(t:string,d:Buffer)=>{const out=Buffer.alloc(8+d.length+(d.length&1));out.write(t,0,'ascii');out.writeUInt32LE(d.length,4);d.copy(out,8);return out;}; const fixtureChunks=[...imageChunks.slice(0,1),make('EXIF',Buffer.from('fake')),make('XMP ',Buffer.from('fake')),...imageChunks.slice(1)]; const riff=Buffer.concat([Buffer.from('RIFF'),Buffer.alloc(4),Buffer.from('WEBP'),...fixtureChunks]);riff.writeUInt32LE(riff.length-8,4); const out=cleanWebp(riff,new Set(['everything'])); const a=parseWebp(riff).chunks.filter(c=>c.type==='VP8 '||c.type==='VP8L').map(c=>sha256(c.data)).join(''); const b=parseWebp(out).chunks.filter(c=>c.type==='VP8 '||c.type==='VP8L').map(c=>sha256(c.data)).join(''); assert.equal(a,b);assert.equal(parseWebp(out).items.length,0);});

test('analysis establishes real dimensions and hashes', async()=>{const img=await sharp({create:{width:3840,height:2160,channels:3,background:{r:1,g:2,b:3}}}).jpeg({quality:90}).toBuffer();const a=await analyze(img,'4k.jpg');assert.equal(a.file.width,3840);assert.equal(a.file.height,2160);assert.equal(a.file.fileHash,sha256(img));assert.equal(a.file.format,'JPEG');});

test('clean performs post-output analysis and pixel verification', async()=>{const img=await sharp({create:{width:256,height:128,channels:3,background:{r:90,g:90,b:90}}}).jpeg({quality:90}).toBuffer();const fixture=makeJpegFixture(img);const {report}=await clean(fixture,'fixture.jpg',{mode:'everything',remove:[],preserveIcc:true});assert.equal(report.integrity.dimensions,true);assert.equal(report.integrity.pixelData,'UNCHANGED');assert.equal(report.after.metadata.present.exif,false);assert.equal(report.after.metadata.present.c2pa,false);});

function tiffFixture(){const ifdOffset=8,entryCount=10,ifdSize=2+entryCount*12+4,bitsOffset=ifdOffset+ifdSize,artistOffset=bitsOffset+6,pixelOffset=artistOffset+4;const b=Buffer.alloc(pixelOffset+12);b.write('II',0,'ascii');b.writeUInt16LE(42,2);b.writeUInt32LE(ifdOffset,4);b.writeUInt16LE(entryCount,ifdOffset);const e=(i:number,tag:number,type:number,count:number,value:number)=>{const o=ifdOffset+2+i*12;b.writeUInt16LE(tag,o);b.writeUInt16LE(type,o+2);b.writeUInt32LE(count,o+4);if(type===3&&count===1)b.writeUInt16LE(value,o+8);else b.writeUInt32LE(value,o+8)};e(0,256,4,1,2);e(1,257,4,1,2);e(2,258,3,3,bitsOffset);e(3,259,3,1,1);e(4,262,3,1,2);e(5,273,4,1,pixelOffset);e(6,277,3,1,3);e(7,278,4,1,2);e(8,279,4,1,12);e(9,315,2,4,artistOffset);b.writeUInt16LE(8,bitsOffset);b.writeUInt16LE(8,bitsOffset+2);b.writeUInt16LE(8,bitsOffset+4);b.write('Ada',artistOffset,'ascii');Buffer.from([255,0,0,0,255,0,0,0,255,255,255,255]).copy(b,pixelOffset);return b}

test('TIFF metadata tag is removed without changing pixel bytes', async()=>{const t=tiffFixture();const before=await analyze(t,'fixture.tif');assert.equal(before.file.format,'TIFF');assert.equal(before.metadata.present.identity,true);const {cleanTiff,parseTiff}=await import('../src/engine/tiff.js');const c=cleanTiff(t,new Set(['everything']));const after=parseTiff(c);assert.equal(after.items.some(x=>x.path==='Artist'),false);const pi1=t.subarray(t.length-12),pi2=c.subarray(c.length-12);assert.deepEqual(pi2,pi1);});

test('malformed JPEG is rejected',()=>{assert.throws(()=>parseJpeg(Buffer.from([0xff,0xd8,0xff,0xe1,0x00])))});

test('8K JPEG analyzes at native resolution', async()=>{const img=await sharp({create:{width:7680,height:4320,channels:3,background:{r:4,g:5,b:6}}}).jpeg({quality:85}).toBuffer();const a=await analyze(img,'8k.jpg');assert.equal(a.file.width,7680);assert.equal(a.file.height,4320);});
test('C2PA structural detection is surfaced without fake validation', async()=>{const base=await sharp({create:{width:64,height:64,channels:3,background:{r:1,g:2,b:3}}}).jpeg().toBuffer();const fixture=makeJpegFixture(base);const a=await analyze(fixture,'c2pa.jpg');assert.equal(a.c2pa.present,true);assert.equal(a.c2pa.validation,'Validation unavailable');assert.equal(a.c2pa.signer,undefined);});
