import { C2paSummary } from '../types/model.js';

const ascii=(b:Uint8Array)=>new TextDecoder('latin1').decode(b);
export function detectC2pa(data:Uint8Array, candidates:string[]): C2paSummary {
  let present=false; let manifestCount=0; const actions:string[]=[]; let software: string|undefined; let created:string|undefined; let signer:string|undefined; let aiGeneration:'Detected'|'Not Detected'|'Unknown'='Unknown';
  const txt=ascii(data.subarray(0, Math.min(data.length, 2_000_000)));
  if(candidates.some(x=>x==='C2PA/JUMBF') || candidates.some(x=>x==='C2PA/Manifest')) present=true;
  if(present){ manifestCount=1; if(/c2pa\.actions|"actions"|Generated|Created|Edited|Resized|Exported/i.test(txt)) actions.push(...['Generated','Edited','Resized','Exported'].filter(a=>new RegExp(a,'i').test(txt))); const sm=txt.match(/(?:software|tool|generator)["'\s:=]+([^\0\r\n]{2,120})/i); if(sm) software=sm[1].trim(); const tm=txt.match(/\b(20\d\d[-:]\d\d[-:]\d\d[^\0\r\n]{0,40})/); if(tm) created=tm[1].trim(); const sg=txt.match(/(?:signer|issuer|organization)["'\s:=]+([^\0\r\n]{2,120})/i); if(sg) signer=sg[1].trim(); if(/ai|machine[- ]generated|generated by|text-to-image/i.test(txt)) aiGeneration='Detected'; }
  return {present,structural:present,validation:'Validation unavailable',signer,created,software,aiGeneration,actions:[...new Set(actions)],manifestCount,warning:present?'Cryptographic C2PA validation unavailable; structural manifest presence only.':''};
}
