import { MetadataItem } from '../types/model.js';
export interface TiffInfo { endian:'LE'|'BE'; bigTiff:boolean; firstIfd:number; tags:Array<{ifd:number;tag:number;type:number;count:number;entryOffset:number;valueOffset:number}>; }
const u16=(d:Uint8Array,o:number,l:boolean)=>l?(d[o]|(d[o+1]<<8)):((d[o]<<8)|d[o+1]); const u32=(d:Uint8Array,o:number,l:boolean)=>l?((d[o]>>>0)|(d[o+1]<<8)|(d[o+2]<<16)|(d[o+3]<<24))>>>0:(((d[o]<<24)>>>0)|(d[o+1]<<16)|(d[o+2]<<8)|d[o+3])>>>0;
export function parseTiff(data:Uint8Array): {info:TiffInfo;items:MetadataItem[]} {
  if(data.length<8) throw new Error('Truncated TIFF');
  const l=data[0]===0x49; if(!l&&!(data[0]===0x4d)) throw new Error('Invalid TIFF byte order');
  const magic=u16(data,2,l);
  if(magic===43) return {info:{endian:l?'LE':'BE',bigTiff:true,firstIfd:0,tags:[]},items:[{path:'BigTIFF',group:'other',value:'BigTIFF detected',source:'TIFF header',confidence:'confirmed',removable:false,reason:'Conservative cleaner does not rewrite BigTIFF'}]};
  if(magic!==42) throw new Error('Unsupported TIFF variant');
  const first=u32(data,4,l); if(first<8||first>=data.length) throw new Error('Invalid TIFF IFD offset');
  const items:MetadataItem[]=[]; const tags:TiffInfo['tags']=[]; const seen=new Set<number>();
  const walk=(ifd:number,depth:number)=>{
    if(!ifd||depth>8||seen.has(ifd)) return; seen.add(ifd);
    if(ifd+2>data.length) throw new Error('Invalid TIFF IFD'); const n=u16(data,ifd,l); if(ifd+2+n*12+4>data.length) throw new Error('Invalid TIFF IFD table');
    for(let i=0;i<n;i++){
      const e=ifd+2+i*12; const tag=u16(data,e,l), type=u16(data,e+2,l), count=u32(data,e+4,l); const size={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8}[type]??1; const bytes=count*size; const valueOffset=bytes<=4?e+8:u32(data,e+8,l); if(valueOffset+bytes>data.length) throw new Error('Invalid TIFF value range'); tags.push({ifd,tag,type,count,entryOffset:e,valueOffset});
      const name=tagNames[tag]??`TIFF tag 0x${tag.toString(16)}`;
      if(tag===34853) items.push({path:'GPSInfo',group:'gps',value:'GPS IFD referenced',source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if(tag===34675) items.push({path:name,group:'technical',value:'ICC profile present',source:'TIFF IFD',confidence:'confirmed',removable:false,reason:'Preserved to avoid color-rendering changes'});
      else if(tag===700) items.push({path:name,group:'xmp',value:'XMP present',source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if([271,272,42033].includes(tag)) items.push({path:name,group:'device',value:`${name} present`,source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if([315,33432,40091,40092,40093].includes(tag)) items.push({path:name,group:'identity',value:`${name} present`,source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if([306,36867,36868].includes(tag)) items.push({path:name,group:'time',value:`${name} present`,source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if([269,270].includes(tag)) items.push({path:name,group:'other',value:`${name} present`,source:'TIFF IFD',confidence:'confirmed',removable:true});
      else if(tag===305) items.push({path:name,group:'software',value:`${name} present`,source:'TIFF IFD',confidence:'confirmed',removable:true});
      if((tag===34665||tag===34853||tag===40965) && type===4 && count===1) walk(valueOffset,depth+1);
    }
    walk(u32(data,ifd+2+n*12,l),depth+1);
  };
  walk(first,0);
  return {info:{endian:l?'LE':'BE',bigTiff:false,firstIfd:first,tags},items};
}
const tagNames:Record<number,string>={256:'ImageWidth',257:'ImageLength',258:'BitsPerSample',259:'Compression',262:'PhotometricInterpretation',270:'ImageDescription',273:'StripOffsets',277:'SamplesPerPixel',278:'RowsPerStrip',279:'StripByteCounts',284:'PlanarConfiguration',305:'Software',315:'Artist',317:'Predictor',320:'ColorMap',338:'ExtraSamples',34675:'ICC_Profile',34853:'GPSInfo',700:'XMP',33432:'Copyright',40091:'XPTitle',40092:'XPComment',40093:'XPAuthor'};
export function cleanTiff(data:Uint8Array, removeGroups:Set<string>):Uint8Array { const parsed=parseTiff(data); if(parsed.info.bigTiff) throw new Error('BigTIFF cleaning is unsupported'); const dropTags=new Set<number>(); for(const t of parsed.info.tags){ if(t.tag===34853&&(removeGroups.has('gps')||removeGroups.has('everything'))) dropTags.add(t.tag); if([270,269].includes(t.tag)&&(removeGroups.has('other')||removeGroups.has('everything'))) dropTags.add(t.tag); if(t.tag===305&& (removeGroups.has('software')||removeGroups.has('everything'))) dropTags.add(t.tag); if([315,33432,40091,40092,40093].includes(t.tag)&&(removeGroups.has('identity')||removeGroups.has('other')||removeGroups.has('everything'))) dropTags.add(t.tag); if([271,272,42033].includes(t.tag)&&(removeGroups.has('device')||removeGroups.has('everything'))) dropTags.add(t.tag); if([306,36867,36868].includes(t.tag)&&(removeGroups.has('time')||removeGroups.has('everything'))) dropTags.add(t.tag); if(t.tag===700&&(removeGroups.has('xmp')||removeGroups.has('everything'))) dropTags.add(t.tag); }
  const l=parsed.info.endian==='LE'; const out=Buffer.from(data); const gpsRoots=parsed.info.tags.filter(t=>t.tag===34853&&t.type===4&&t.count===1).map(t=>t.valueOffset); const zeroedIfds=new Set<number>(); const zeroIfd=(off:number)=>{ if(!off||zeroedIfds.has(off)||off>=data.length)return; zeroedIfds.add(off); const n=u16(data,off,l); const end=off+2+n*12+4; if(end>data.length)return; for(let i=0;i<n;i++){const e=off+2+i*12;const tag=u16(data,e,l),type=u16(data,e+2,l),count=u32(data,e+4,l);const size={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8}[type]??1;const bytes=count*size;const vo=bytes<=4?e+8:u32(data,e+8,l); if(bytes>4&&!parsed.info.tags.some(t=>t.entryOffset===e&&!dropTags.has(t.tag))) out.fill(0,vo,Math.min(vo+bytes,out.length)); if((tag===34665||tag===34853||tag===40965)&&type===4&&count===1) zeroIfd(vo);} out.fill(0,off,end); }; if(removeGroups.has('gps')||removeGroups.has('everything')) gpsRoots.forEach(zeroIfd); const keptValueRanges=parsed.info.tags.filter(t=>!dropTags.has(t.tag)&&t.count>0).map(t=>{ const size={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8}[t.type]??1; const bytes=t.count*size; return {start:bytes<=4?t.entryOffset+8:t.valueOffset,end:(bytes<=4?t.entryOffset+8:t.valueOffset)+bytes}; }); const ifdOffsets=[...new Set(parsed.info.tags.map(t=>t.ifd))].filter(ifd=>!zeroedIfds.has(ifd)); for(const ifd of ifdOffsets){ const count=u16(data,ifd,l); const entries=[] as Uint8Array[]; for(let i=0;i<count;i++){ const e=ifd+2+i*12; const tag=u16(data,e,l); if(!dropTags.has(tag)) entries.push(data.subarray(e,e+12)); else { const t=parsed.info.tags.find(x=>x.entryOffset===e); if(t && t.count){ const size={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8}[t.type]??1; const bytes=t.count*size; if(bytes>4){ const start=t.valueOffset,end=start+bytes; const overlaps=keptValueRanges.some(r=>start<r.end&&end>r.start); if(!overlaps) out.fill(0,start,end); } } } } const newSize=entries.length*12; if(newSize!==count*12) { const next=ifd+2+count*12+4; const following=[...parsed.info.tags.map(t=>t.valueOffset)].filter(v=>v>next); const nextOffset=Math.min(...following,data.length); if(next+(count-entries.length)*12>nextOffset) throw new Error('TIFF metadata cannot be removed safely without relocating referenced data'); const tableEnd=ifd+2+count*12; for(let i=0;i<entries.length;i++) entries[i].forEach((v,j)=>out[ifd+2+i*12+j]=v); const newNextPos=ifd+2+newSize; const nextValue=data.subarray(tableEnd,tableEnd+4); nextValue.forEach((v,j)=>out[newNextPos+j]=v); out.fill(0,newNextPos+4,tableEnd+4); } }
  return out;
}
