import { IncomingMessage, ServerResponse } from 'node:http';
import { HttpError } from './errors.js';
import { config } from './config.js';
import { detectFormat } from '../engine/formats.js';

const hits=new Map<string,{start:number;count:number}>();
export function clientIp(req:IncomingMessage):string { return (req.socket.remoteAddress??'unknown').replace(/^::ffff:/,''); }
export function rateLimit(req:IncomingMessage):void { const ip=clientIp(req); const now=Date.now(); const item=hits.get(ip); if(!item||now-item.start>config.rateLimitWindowMs){hits.set(ip,{start:now,count:1});return;} item.count++; if(item.count>config.rateLimitMax) throw new HttpError(429,'Rate limit exceeded','RATE_LIMIT'); }
export function headers(res:ServerResponse):void { const allowedOrigins=['https://metaclean-4k.vercel.app','https://metaclean-4k-52zcjkvcl-adwaithv964s-projects.vercel.app']; res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS'); res.setHeader('Access-Control-Allow-Headers','Content-Type, Content-Length'); res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('X-Frame-Options','DENY'); res.setHeader('Referrer-Policy','no-referrer'); res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()'); res.setHeader('Cache-Control','no-store'); }
const allowedExt=new Set(['jpg','jpeg','png','webp','tif','tiff','heic','heif','avif']);
export function validateUpload(name:string, clientMime:string|undefined, data:Buffer):{format:string;mime:string}{ const clean=name.split(/[\\/]/).pop()??'image'; const ext=clean.includes('.')?clean.slice(clean.lastIndexOf('.')+1).toLowerCase():''; if(!allowedExt.has(ext)) throw new HttpError(415,'Unsupported file extension','UNSUPPORTED_FORMAT'); const format=detectFormat(data); if(format==='UNKNOWN') throw new HttpError(415,'File signature is not a supported image format','BAD_MAGIC'); if(format==='JPEG' && !['jpg','jpeg'].includes(ext)) throw new HttpError(400,'Extension does not match JPEG signature','EXT_MISMATCH'); if(format==='PNG'&&ext!=='png')throw new HttpError(400,'Extension does not match PNG signature','EXT_MISMATCH'); if(format==='WEBP'&&ext!=='webp')throw new HttpError(400,'Extension does not match WebP signature','EXT_MISMATCH'); if(format==='TIFF'&&!['tif','tiff'].includes(ext))throw new HttpError(400,'Extension does not match TIFF signature','EXT_MISMATCH'); const m={JPEG:'image/jpeg',PNG:'image/png',WEBP:'image/webp',TIFF:'image/tiff',HEIC:'image/heic',HEIF:'image/heif',AVIF:'image/avif'}[format]??'application/octet-stream'; if(clientMime&&clientMime!=='application/octet-stream'&&clientMime!==m) throw new HttpError(400,'Declared MIME type does not match detected format','MIME_MISMATCH'); return {format,mime:m}; }
